USE [master]
GO
/****** Object:  Database [Training]    Script Date: 7/4/2025 12:23:00 PM ******/
CREATE DATABASE [Training]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Training', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.SQL2016\MSSQL\DATA\Training.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Training_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.SQL2016\MSSQL\DATA\Training_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO
ALTER DATABASE [Training] SET COMPATIBILITY_LEVEL = 130
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Training].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [Training] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [Training] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [Training] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [Training] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [Training] SET ARITHABORT OFF 
GO
ALTER DATABASE [Training] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [Training] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [Training] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [Training] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [Training] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [Training] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [Training] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [Training] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [Training] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [Training] SET  DISABLE_BROKER 
GO
ALTER DATABASE [Training] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [Training] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [Training] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [Training] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [Training] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [Training] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [Training] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [Training] SET RECOVERY FULL 
GO
ALTER DATABASE [Training] SET  MULTI_USER 
GO
ALTER DATABASE [Training] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [Training] SET DB_CHAINING OFF 
GO
ALTER DATABASE [Training] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [Training] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [Training] SET DELAYED_DURABILITY = DISABLED 
GO
EXEC sys.sp_db_vardecimal_storage_format N'Training', N'ON'
GO
ALTER DATABASE [Training] SET QUERY_STORE = OFF
GO
USE [Training]
GO
ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO
ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO
ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO
ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO
USE [Training]
GO
/****** Object:  User [Training]    Script Date: 7/4/2025 12:23:01 PM ******/
CREATE USER [Training] FOR LOGIN [Training] WITH DEFAULT_SCHEMA=[dbo]
GO
ALTER ROLE [db_owner] ADD MEMBER [Training]
GO
ALTER ROLE [db_accessadmin] ADD MEMBER [Training]
GO
ALTER ROLE [db_datareader] ADD MEMBER [Training]
GO
ALTER ROLE [db_datawriter] ADD MEMBER [Training]
GO
/****** Object:  Table [dbo].[Department]    Script Date: 7/4/2025 12:23:01 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Department](
	[Id] [bigint] IDENTITY(1,1) NOT NULL,
	[Name] [varchar](15) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Employee]    Script Date: 7/4/2025 12:23:01 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Employee](
	[Id] [bigint] IDENTITY(1,1) NOT NULL,
	[Username] [nvarchar](15) NOT NULL,
	[Password] [nvarchar](15) NOT NULL,
	[Email] [nvarchar](255) NOT NULL,
	[RoleId] [nvarchar](255) NOT NULL,
	[Phone_Number] [decimal](8, 0) NOT NULL,
	[Birthdate] [date] NOT NULL,
	[Living_Address] [varchar](30) NOT NULL,
	[Gender] [char](1) NOT NULL,
	[Salary] [int] NOT NULL,
	[MaritalStatusId] [int] NOT NULL,
	[DepartmentId] [bigint] NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Task]    Script Date: 7/4/2025 12:23:01 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Task](
	[Id] [bigint] IDENTITY(1,1) NOT NULL,
	[Name] [varchar](15) NOT NULL,
	[DepartmentId] [bigint] NULL,
	[CreationDate] [date] NOT NULL,
	[ClosreDate] [date] NOT NULL,
	[StatusId] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TaskAssignment]    Script Date: 7/4/2025 12:23:01 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TaskAssignment](
	[Id] [bigint] NOT NULL,
	[TaskId] [bigint] NULL,
	[EmployeeId] [bigint] NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TimeSlice]    Script Date: 7/4/2025 12:23:01 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TimeSlice](
	[Id] [bigint] NOT NULL,
	[TaskAssignmentId] [bigint] NULL,
	[StartDate] [date] NOT NULL,
	[EndDate] [date] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET IDENTITY_INSERT [dbo].[Department] ON 
GO
INSERT [dbo].[Department] ([Id], [Name]) VALUES (1, N'Dev')
GO
SET IDENTITY_INSERT [dbo].[Department] OFF
GO
SET ANSI_PADDING ON
GO
/****** Object:  Index [UQ__Departme__737584F64020C741]    Script Date: 7/4/2025 12:23:01 PM ******/
ALTER TABLE [dbo].[Department] ADD UNIQUE NONCLUSTERED 
(
	[Name] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
/****** Object:  Index [UQ__Employee__17A35CA464B8E893]    Script Date: 7/4/2025 12:23:01 PM ******/
ALTER TABLE [dbo].[Employee] ADD UNIQUE NONCLUSTERED 
(
	[Phone_Number] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
SET ANSI_PADDING ON
GO
/****** Object:  Index [UQ__Employee__536C85E4787B3AE1]    Script Date: 7/4/2025 12:23:01 PM ******/
ALTER TABLE [dbo].[Employee] ADD UNIQUE NONCLUSTERED 
(
	[Username] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
SET ANSI_PADDING ON
GO
/****** Object:  Index [UQ__Employee__A9D10534BA3FCE27]    Script Date: 7/4/2025 12:23:01 PM ******/
ALTER TABLE [dbo].[Employee] ADD UNIQUE NONCLUSTERED 
(
	[Email] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
SET ANSI_PADDING ON
GO
/****** Object:  Index [UQ__Task__737584F67634B248]    Script Date: 7/4/2025 12:23:01 PM ******/
ALTER TABLE [dbo].[Task] ADD UNIQUE NONCLUSTERED 
(
	[Name] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Employee]  WITH CHECK ADD FOREIGN KEY([DepartmentId])
REFERENCES [dbo].[Department] ([Id])
ON UPDATE CASCADE
ON DELETE SET NULL
GO
ALTER TABLE [dbo].[Task]  WITH CHECK ADD FOREIGN KEY([DepartmentId])
REFERENCES [dbo].[Department] ([Id])
ON UPDATE CASCADE
ON DELETE SET NULL
GO
ALTER TABLE [dbo].[TaskAssignment]  WITH CHECK ADD FOREIGN KEY([EmployeeId])
REFERENCES [dbo].[Employee] ([Id])
ON UPDATE CASCADE
ON DELETE SET NULL
GO
ALTER TABLE [dbo].[TaskAssignment]  WITH CHECK ADD FOREIGN KEY([TaskId])
REFERENCES [dbo].[Task] ([Id])
GO
ALTER TABLE [dbo].[TimeSlice]  WITH CHECK ADD FOREIGN KEY([TaskAssignmentId])
REFERENCES [dbo].[TaskAssignment] ([Id])
ON UPDATE CASCADE
ON DELETE SET NULL
GO
USE [master]
GO
ALTER DATABASE [Training] SET  READ_WRITE 
GO
